// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgbsbvwqjoxqpexoorff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnYnNidndxam94cXBleG9vcmZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkzMjcwNjAsImV4cCI6MjA4NDkwMzA2MH0.cExdXp7KJ0u_97qg4X2BeRRmy5t-6ajEj3xDt9QimkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});